### ISSUE TITLE
Mac running .so issue

### ISSUE THREAD

**Issue by zj00377** [EricSteinberger/DREAM#3]
Hi Eric, 

I have the same issue as the one open issue in DeepCFR while I am running either DeepCFR or Dream. Do you have any idea how to address this issue? It quite expansive to run the same experiment on AWS for 1 week, I would like to use my own Mac pro to test the code alternatively. 

self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Deep-CFR/DeepCFR/PokerRL/game/_/cpp_wrappers/lib_luts.so, 6): no suitable image found.  Did find:
	/Deep-CFR/DeepCFR/PokerRL/game/_/cpp_wrappers/lib_luts.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Deep-CFR/DeepCFR/PokerRL/game/_/cpp_wrappers/lib_luts.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

Thanks a lot,
Joena

**Comment by diditforlulz273** [comment]
Sorry for meddling here and not being Eric, but .so is a compiled library for general Linux like Ubuntu/RedHat/CentOS etc., and normally it does not work on Mac(although it is Unix-derived), like you won't be able to use win32 PE .dll here.

**Comment by EricSteinberger** [comment]
Hi! Thanks for your interest in my code.

@diditforlulz273 is right about how it's compiled.

The reason I used AWS is that running it on your Macbook would take _a lot_ longer than one week or, in the case of FHP experiments, be impossible because you need too much RAM. As a rule of thumb, if it's expensive on AWS, it won't run on your Macbook.

Running Leduc on AWS for one run will literally cost you cents, not even full dollars. Anything bigger than Leduc won't run on your Mac anyway... Also: it should cost you a few 10s of dollars to run one FHP experiment and a few 100s to run the full suite of experiments we ran if you use AWS spot instances.

Thanks,
Eric
